service: <%= fileName %>

custom:
  webpack:
    packager: 'yarn'
    includeModules: true # enable auto-packing of external modules
    forceExclude:
      - aws-sdk

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-bespoken
  - serverless-offline
  

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  memorySize: 128
  versionFunctions: false
  region: eu-west-1

functions:
  skill:
    handler: src/index.handler
    events:
      - alexaSkill
        appId: amzn1.ask.skill.xx-xx-xx-xx